[broker]
host = "127.0.0.1"
port = 8883

[identity]
site_id = "rvce-plant-A"
stack_id = "stack-03"
sensor_id = "h2_purity"
client_cn = "sensor-h2_purity-03"

[certs]
ca = "../../certs/ca/ca.crt"
cert = "../../certs/clients/sensor-h2_purity-03/client.crt"
key = "../../certs/clients/sensor-h2_purity-03/client.key"

[publish]
qos = 1
interval_seconds = 3

